- name: Add multiverse to apt-repos
  apt_repository:
    repo: "{{item}}"
    update_cache: no # We will do ourselfs afterwards
  register: multiverse_installed
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
  sudo: yes

- name: Update apt-cache with multiverse
  apt: update_cache=yes
  when: multiverse_installed | changed
  sudo: yes